fix bug not getting page types for empty category name
celements/celements-core pull request #100
Opened 2017-01-31 18:59 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-406

2017-02-02 21:47 UTC, fpichler requested changes

2017-02-02 21:47 UTC, fpichler commented on src/main/java/com/celements/pagetype/service/PageTypeService.java
> +  private Map<String, IPageTypeCategoryRole> getTypeNameToCategoryMap(boolean deprecated) {
please do not add a boolean to the getTypeNameToCategoryMap. This binds the implementation to the interface. Instead rename getTypeNameToCategoryMap to void loadTypeNameToCategoryMap. Then implement getTypeNameToCategoryMap returning only the not deprecated names (as before) and getTypeNameToCategoryMapIncludeDeprecated returning typeNameToCatCacheDeprecated. Call the loadTypeNameToCategoryMap at the beginning of both get methods.

2017-02-02 21:57 UTC, fpichler commented on src/main/java/com/celements/pagetype/service/PageTypeService.java
> +  private Map<String, IPageTypeCategoryRole> getTypeNameToCategoryMap(boolean deprecated) {
More Details in Martin Fowler: Refactoring p. 279 (Separate Query from Modifier)

2017-02-03 11:52 UTC, ebeutler commented
changed, even though, I'm not sure why changing the signature of a private method should bind the implementation to the interface.

2017-02-03 12:07 UTC, fpichler requested changes

2017-02-03 12:07 UTC, fpichler commented on src/main/java/com/celements/pagetype/service/PageTypeService.java
> +            for (String deprecateName : typeCategory.getDeprecatedNames()) {
use getAllTypeNames instead of getDeprecatedNames

2017-02-03 12:07 UTC, fpichler commented on src/main/java/com/celements/pagetype/service/PageTypeService.java
> +    completeMap.putAll(typeNameToCatCache);
using use getAllTypeNames instead of getDeprecatedNames: this readding over and over again is not needed.

2017-02-03 12:07 UTC, fpichler commented on src/main/java/com/celements/pagetype/service/PageTypeService.java
> +    loadTypeNameToCategoryMap();
additional loadTypeNameToCategoryMap not needed.

2017-02-03 12:07 UTC, fpichler commented on src/main/java/com/celements/pagetype/service/PageTypeService.java
> +  private void loadTypeNameToCategoryMap() {
maybe plural is better loadTypeNameCategoryMaps because we load to different maps.

2017-02-05 12:22 UTC, fpichler approved these changes

2017-02-06 09:38 UTC, merged