Enum reverse lookup thread safety.
celements/celements-core pull request #103
Opened 2017-02-07 17:59 UTC by nderguti

https://synjira.atlassian.net/browse/CELDEV-441
Replaced HashMap<> to ReverseMap<> in all enum's.

2017-02-14 10:35 UTC, msladek requested changes

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/metatag/MetaTagScriptService.java
> +    ECharset charset = ECharset.getCharset(charsetStr).get();
This could cause a NPE, instead resolve Optionals by checking present() first

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/metatag/enums/ECharset.java
> +    return identifier;
use getIdentifier() insteand (applies to all changed Enums)

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/metatag/enums/EHttpEquiv.java
>    @Nullable
should be NotNull

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/metatag/enums/ENameStandard.java
>    @Nullable
should be NotNull

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/metatag/enums/EReferrer.java
>    @Nullable
should be NotNull

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/rights/access/RightsAccessScriptService.java
> +    return EAccessLevel.getAccessLevel(xwikiRight).get();
This could cause a NPE, instead resolve Optionals by checking present() first

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/rights/access/DefaultRightsAccessFacade.java
> +    return hasAccessLevel(entityRef, EAccessLevel.getAccessLevel(right).get(), user);
This could cause a NPE, instead resolve Optionals by checking present() first

2017-02-14 10:35 UTC, msladek commented on src/main/java/com/celements/model/classes/fields/list/AccessRightLevelsField.java
> +      ret.add(EAccessLevel.getAccessLevel(elem.toString()).get());
This could cause a NPE, instead resolve Optionals by checking present() first

2017-02-14 15:45 UTC, nderguti commented on src/main/java/com/celements/rights/access/RightsAccessScriptService.java
> +    return EAccessLevel.getAccessLevel(xwikiRight).get();
@msladek I used here: return EAccessLevel.getAccessLevel(xwikiRight).orNull(); which checks if it is present and gets it, if not present it returns null.

2017-02-15 10:41 UTC, msladek requested changes

2017-02-15 10:41 UTC, msladek commented on src/main/java/com/celements/metatag/MetaTagScriptService.java
> +      if (charset != null) {
null check unnecessary

2017-02-15 10:41 UTC, msladek commented on src/main/java/com/celements/model/classes/fields/list/AccessRightLevelsField.java
> +        ret.add(EAccessLevel.getAccessLevel(elem.toString()).get());
extract `EAccessLevel.getAccessLevel(elem.toString())` to local variable

2017-02-15 10:41 UTC, msladek commented on src/main/java/com/celements/rights/access/DefaultRightsAccessFacade.java
> +      return hasAccessLevel(entityRef, EAccessLevel.getAccessLevel(right).get(), user);
extract `EAccessLevel.getAccessLevel(right)` to local variable

2017-02-15 16:44 UTC, msladek approved these changes
thanks for the changes, looks good to me :+1: 

resolve conflicts and then "Squash&Merge"

2017-02-21 10:11 UTC, merged

2017-02-21 16:28 UTC, ebeutler commented
Code did not compile!

This merge removed a required `import com.google.common.base.Strings;` in MetaTagScriptService which lead to compile errors and failing Jenkins builds.

2017-02-22 12:05 UTC, msladek commented
it is a good practice to run all unit tests for the project before merging