add component hook to add meta tags to the header
celements/celements-core pull request #104
Opened 2017-02-22 17:10 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-389

2017-02-22 18:02 UTC, msladek requested changes

2017-02-22 18:02 UTC, msladek commented on src/main/java/com/celements/metatag/MetaTagHeaderRole.java
> +public interface MetaTagHeaderRole {
rename to MetaTagProviderRole and add `public @NotNull List<MetaTag> getBodyMetaTags();` as well since meta tags are allowed in body too for HTML5

2017-02-22 18:02 UTC, msladek commented on src/main/java/com/celements/metatag/MetaTagServiceRole.java
> +  public void loadHeaderTags();
collectHeaderTags / collectBodyTags

2017-02-24 14:04 UTC, msladek approved these changes

2017-02-26 17:12 UTC, fpichler approved these changes

2017-03-06 13:58 UTC, merged