isLoggedIn() method
celements/celements-core pull request #107
Opened 2017-03-31 13:22 UTC by nderguti

https://synjira.atlassian.net/browse/CELDEV-472

2017-03-31 14:29 UTC, msladek requested changes

2017-03-31 14:29 UTC, msladek commented on src/main/java/com/celements/rights/access/RightsAccessScriptService.java
> +    return false;
use `rightsAccess.isLoggedIn()` instead of reimplementing the method

2017-03-31 14:29 UTC, msladek commented on src/main/java/com/celements/rights/access/DefaultRightsAccessFacade.java
> +      return true;
for clarity reasons, it's preferable to only have one return statement at the end of the method, e.g.:
```
boolean ret = ...;
LOGGER...
return ret;

2017-03-31 14:29 UTC, msladek commented
also add unit tests for RightsService

2017-04-04 15:28 UTC, ebeutler requested changes

2017-04-04 15:28 UTC, ebeutler commented on src/main/java/com/celements/rights/access/RightsAccessScriptService.java
> +  XWikiContext xWikiContext;
1. XWikiContext isn't a component, so this wouldn't work.
2. xWikiContext is not used.
-> please remove

2017-04-04 15:28 UTC, ebeutler commented on src/main/java/com/celements/rights/access/DefaultRightsAccessFacade.java
> +    if (!"XWiki.XWikiGuest".equals(getContext().getUser())) {
Please use XWikiRightService.GUEST_USER_FULLNAME instead of hard coded String (same applies in the tests)

2017-04-04 15:28 UTC, ebeutler commented on src/main/java/com/celements/rights/access/DefaultRightsAccessFacade.java
> +    boolean ret;
Please initialise to make the current value explicit.

2017-04-04 15:28 UTC, ebeutler commented on src/main/java/com/celements/rights/access/DefaultRightsAccessFacade.java
> +      ret = false;
No need to set again, since this is the same as the default value.

2017-04-06 08:24 UTC, ebeutler approved these changes

2017-04-06 13:42 UTC, msladek requested changes

2017-04-06 13:42 UTC, msladek commented on src/main/java/com/celements/rights/access/DefaultRightsAccessFacade.java
> +    if (!XWikiRightService.GUEST_USER_FULLNAME.equals(getContext().getUser())) {
again there is no need for an if. also, the logger never prints `ret`. why not do it like that?
```
boolean ret = ...;
LOGGER.info("isLoggedIn: {}", ret);
return ret;
```

2017-04-11 13:13 UTC, msladek approved these changes

2017-04-11 13:29 UTC, merged