Email Validation not available in Class Definitions
celements/celements-core pull request #108
Opened 2017-04-04 15:50 UTC by nderguti

https://synjira.atlassian.net/browse/CELDEV-477

2017-04-06 08:22 UTC, ebeutler requested changes

2017-04-06 08:22 UTC, ebeutler commented on src/main/java/com/celements/mailsender/CelMailSenderService.java
> +  public static final String EMAIL_VALIDATION_REGEX_CLASS_DEFINITIONS = "/^[\\w\\-\\u0153\\u00E0-\\u00F6\\u00F8-\\u00FF.+]+[@][\\w\\-\""
Use EMAIL_VALIDATION_REGEX when building EMAIL_VALIDATION_REGEX_CLASS_DEFINITIONS

2017-04-06 08:22 UTC, ebeutler commented on src/main/java/com/celements/mailsender/CelMailSenderService.java
> -    // chars - a-z A-Z 0-9 œ à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ø ù ú û ü ý þ ÿ
Add this comment to EMAIL_VALIDATION_REGEX. It's much more readable than "\\w\\-\\u0153\\u00E0-\\u00F6\\u00F8-\\u00FF" if out want to no which characters are allowed.

2017-04-06 13:45 UTC, msladek requested changes
agree with @ebeutler

2017-04-11 09:35 UTC, ebeutler requested changes

2017-04-11 09:35 UTC, ebeutler commented on src/main/java/com/celements/mailsender/CelMailSenderService.java
>      // chars - a-z A-Z 0-9 œ à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ø ù ú û ü ý þ ÿ
please move the commen to the constant (around line 17)

2017-04-11 10:55 UTC, ebeutler approved these changes

2017-04-11 13:14 UTC, msladek approved these changes

2017-04-11 13:31 UTC, merged