XObject-Bean Converter
celements/celements-core pull request #109
Opened 2017-04-16 20:58 UTC by msladek

2017-04-20 16:06 UTC, ebeutler requested changes

2017-04-20 16:06 UTC, ebeutler commented on src/main/java/com/celements/convert/bean/BeanFieldAccessor.java
> +      // expected to happen for all non list fields
Could you add a debug or trace log

2017-04-21 10:57 UTC, ebeutler approved these changes

2017-04-25 20:30 UTC, fpichler approved these changes

2017-04-26 09:59 UTC, merged