ClassDefinition CustomListField & Marshallers
celements/celements-core pull request #112
Opened 2017-06-27 19:40 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-510

2017-06-28 13:18 UTC, ebeutler requested changes

2017-06-28 13:18 UTC, ebeutler commented on src/main/java/com/celements/model/classes/fields/list/ListField.java
> +      // TODO log
open TODO

2017-06-29 04:46 UTC, fpichler requested changes

2017-06-29 04:46 UTC, fpichler commented on src/main/java/com/celements/marshalling/Marshaller.java
> +  public @NotNull Object serialize(@NotNull T val);
Replace Object with String. If a more general solution is needed (use case ?) then use generic S instead.

2017-06-30 06:03 UTC, fpichler approved these changes

2017-06-30 15:09 UTC, ebeutler approved these changes

2017-06-30 15:09 UTC, merged