Release 2.91
celements/celements-core pull request #131
Opened 2017-08-31 15:29 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-545

2017-09-01 12:38 UTC, ebeutler requested changes
should remain 1.169-SNAPSHOT until final release

2017-09-06 19:20 UTC, fpichler approved these changes

2017-09-06 19:22 UTC, fpichler commented
@ebeutler We have never done an RC for the components. Thus this is already a final 1.169 release. Please approve and merge.

2017-09-07 13:11 UTC, ebeutler approved these changes

2017-09-07 13:11 UTC, merged