LocalEventListener improve logging for missing serializability
celements/celements-core pull request #161
Opened 2018-04-23 11:09 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-665

improves logging and prevents logfile flooding.

2018-04-25 21:52 UTC, fpichler requested changes

2018-04-25 21:52 UTC, fpichler commented on src/main/java/com/celements/common/observation/listener/LocalEventListener.java
> +    if (!(data instanceof Serializable)) {
"instanceof Serializable" is not sufficient for checkSerializability. Please test by serializing the data and catching the exception.

2018-04-26 12:53 UTC, msladek commented on src/main/java/com/celements/common/observation/listener/LocalEventListener.java
> +        if (containsNotSerializableException(exc)) {
Note: `NotSerializableException` is a checked exception and not in the signature of onEvent, hence I cannot simply add a `catch(NotSerializableException nse)` block but have to analyse the given `Exception`

2018-04-26 13:38 UTC, ebeutler approved these changes

2018-04-26 16:00 UTC, fpichler requested changes

2018-04-26 16:00 UTC, fpichler commented on src/main/java/com/celements/common/observation/listener/LocalEventListener.java
> +  final Map<Class<? extends Event>, LogCounter> logCountMap = new ConcurrentHashMap<>();
Please make pivate?

2018-04-26 16:00 UTC, fpichler commented on src/main/java/com/celements/common/observation/listener/LocalEventListener.java
> +    final long time = System.currentTimeMillis();
Please make the fields private

2018-04-27 09:33 UTC, fpichler approved these changes

2018-04-27 09:35 UTC, fpichler commented
I understand now the need to access the properies from testing. Yet, it is a smell and we must improve it later on. Please add an Jira-Issue.

2018-04-28 11:28 UTC, merged