CelementsWebService encodeUrl instead use URIBuilder
celements/celements-core pull request #174
Opened 2018-06-25 04:09 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-645

2018-06-25 09:18 UTC, fpichler requested changes

2018-06-25 09:18 UTC, fpichler commented on src/main/java/com/celements/web/service/CelementsWebService.java
> +      LOGGER.info("encodeUrlForRedirect - [{}] from [{}]", uri, urlStr);
please ensure that uri.toString() is logged and not the Object-Address

2018-06-25 16:36 UTC, fpichler approved these changes

2018-06-25 16:37 UTC, fpichler commented
Please let Dari check this PR too.

2018-06-26 13:29 UTC, dkhasham approved these changes

2018-06-26 15:37 UTC, merged