add formLayout field to FormConfigClass
celements/celements-core pull request #190
Opened 2018-12-31 17:04 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-778

2019-01-09 08:27 UTC, msladek approved these changes

2019-01-09 08:27 UTC, msladek commented on src/main/java/com/celements/webform/ActionService.java
> +      execAct = modelAccess.getDocument(new DocumentReference("celements2web", "Macros",
- use `References#create` instead of `new`. it will create immutable references.
- use constant for `celements2web` (is there one?)

2019-01-09 08:27 UTC, msladek commented on src/main/java/com/celements/webform/ActionService.java
> +    final Object configScriptDebug = configSource.getProperty("actionScriptDebug");
naming: config source properties we normally head with project and component name e.g. 
```suggestion
    final Object configScriptDebug = configSource.getProperty("celements.action.scriptDebug");
```

2019-01-09 08:28 UTC, msladek requested changes
changes requested, sorry it took so long

2019-01-10 21:53 UTC, fpichler commented on src/main/java/com/celements/webform/ActionService.java
> +      execAct = modelAccess.getDocument(new DocumentReference("celements2web", "Macros",
no, unfortunately we have not yet moved celements2web to the config document.

2019-01-11 14:49 UTC, msladek approved these changes

2019-01-11 15:01 UTC, merged