DocFormCommand: serial doc load&save
celements/celements-core pull request #251
Opened 2020-05-18 00:46 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-899

2020-05-19 11:48 UTC, fpichler requested changes

2020-05-19 11:48 UTC, fpichler commented on src/main/java/com/celements/docform/DocFormCommand.java
> +public class DocFormCommand implements IDocForm {
this is no Command anymore. Thus please rename to DocFormService or DocFormDefault or similar.

2020-05-19 15:50 UTC, msladek commented on src/main/java/com/celements/docform/DocFormCommand.java
> +public class DocFormCommand implements IDocForm {
The class still conforms to the command pattern, this behaviour wasn't changed with this PR.
The object instantiation is now handled by the `ComponentManager` with `@InstantiationStrategy(PER_LOOKUP)` for dependency management, but that doesn't qualify the class as a `Service` imho.

2020-05-19 16:00 UTC, fpichler submitted a review, later dismissed

2020-05-19 16:00 UTC, fpichler commented on src/main/java/com/celements/docform/DocFormCommand.java
> +public class DocFormCommand implements IDocForm {
ok. I see your point: https://alvinalexander.com/java/java-command-design-pattern-in-java-examples/

2020-05-19 19:47 UTC, msladek commented
resolved merge conflicts

2020-05-20 17:48 UTC, fpichler approved these changes

2020-05-20 18:23 UTC, merged