CELDEV-1198 - ContentDynLoad must pass through request parameters
celements/celements-core pull request #366
Opened 2023-10-14 22:10 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-1198

2023-10-14 23:43 UTC, msladek requested changes

2023-10-14 23:43 UTC, msladek commented on src/main/java/com/celements/navigation/presentation/RenderedContentDynLoadPresentationType.java
> +import org.springframework.stereotype.Component;
also remove from components.txt

2023-10-15 13:36 UTC, fpichler commented on src/main/java/com/celements/navigation/presentation/RenderedContentDynLoadPresentationType.java
> +import org.springframework.stereotype.Component;
done

2023-10-15 18:52 UTC, msladek approved these changes

2023-10-15 19:37 UTC, merged