implementing getFieldValue (CELDEV-353)
celements/celements-core pull request #84
Opened 2016-10-01 17:28 UTC by fpichler

CELDEV-353 : https://synjira.atlassian.net/browse/CELDEV-353

2016-10-01 17:29 UTC, fpichler commented
please review and merge if okay.

2016-10-03 11:35 UTC, msladek requested changes
thanks for these additions

2016-10-03 11:35 UTC, msladek commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    return Optional.fromNullable(getProperty(checkNotNull(doc), checkNotNull(field)));
`checkNotNull(doc)` already happens in _getXObjects_ Line 430

2016-10-03 11:35 UTC, msladek commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    return Optional.fromNullable(getProperty(checkNotNull(docRef), checkNotNull(field)));
`checkNotNull(docRef)` already happens in _getDocumentReadOnly_ Line 136

2016-10-03 11:35 UTC, msladek commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
>    public <T> T getProperty(DocumentReference docRef, ClassField<T> field)
perhaps we want to discourage using this method in favour of Optional return values by marking it as deprecated?

2016-10-04 16:57 UTC, fpichler commented
please fix first https://synjira.atlassian.net/browse/CELDEV-355

2016-10-04 17:22 UTC, fpichler commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    return Optional.fromNullable(getProperty(checkNotNull(doc), checkNotNull(field)));
This is right. Over five more embedded method calls in the current implementation. Yet, fast failure means checking early.

2016-10-04 17:23 UTC, fpichler commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    return Optional.fromNullable(getProperty(checkNotNull(docRef), checkNotNull(field)));
This is right. Over four more embedded method calls in the current implementation. Yet, fast failure means checking early.

2016-10-04 17:24 UTC, fpichler commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
>    public <T> T getProperty(DocumentReference docRef, ClassField<T> field)
this could be a later discussion. Is not the focus of this issue.

2016-10-12 16:14 UTC, msladek approved these changes

2016-10-12 16:14 UTC, merged