add AccessRightLevelsField, ListOfGroupsField and ListOfUsersField
celements/celements-core pull request #90
Opened 2016-11-26 17:16 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-379

2016-11-26 17:46 UTC, fpichler requested changes
can you please add at least one TestClass using this fields in a unit test?

Edit Marc: Add a test class for each new field type.

2016-11-28 12:08 UTC, msladek requested changes

2016-11-28 12:08 UTC, msladek commented on src/main/java/com/celements/model/classes/fields/list/AccessRightLevelsField.java
> +public final class AccessRightLevelsField extends StringListField {
Extend _EnumListField\<EAccessLevel>_ and overwrite _getListClass()_ and if needed also _serialize(List\<EAccessLevel>)_ and _resolveList(List\<?>)_

2016-11-28 12:08 UTC, msladek commented on src/main/java/com/celements/model/classes/fields/list/ListOfUsersField.java
> +public final class ListOfUsersField extends StringListField {
Extend _ListField\<XWikiUser>_

2016-12-05 15:13 UTC, msladek requested changes

2016-12-05 15:13 UTC, msladek commented on src/main/java/com/celements/model/classes/fields/list/AccessRightLevelsField.java
> +        enumType.getEnumConstants())).transform(GET_ACCESS_LEVEL_ENUM_IDENTIFIERS)));
element.fromString only returns a BaseProperty, it doesn't change the LevelsClass. i guess the method only returns a new LevelsClass?

2016-12-05 15:13 UTC, msladek commented on src/main/java/com/celements/model/classes/fields/list/ListOfUsersField.java
> +      ret.add(new XWikiUser(elem.toString()));
is it a good idea at this place to check the existence of the XWikiUser doc/obj before adding it to the list?

2016-12-05 15:41 UTC, ebeutler commented on src/main/java/com/celements/model/classes/fields/list/AccessRightLevelsField.java
> +        enumType.getEnumConstants())).transform(GET_ACCESS_LEVEL_ENUM_IDENTIFIERS)));
you're right, seems not to change anything -.-

2016-12-05 15:53 UTC, ebeutler commented on src/main/java/com/celements/model/classes/fields/list/ListOfUsersField.java
> +      ret.add(new XWikiUser(elem.toString()));
@fpichler WDYT?

2016-12-05 16:40 UTC, ebeutler commented on src/main/java/com/celements/model/classes/fields/list/ListOfUsersField.java
> +      ret.add(new XWikiUser(elem.toString()));
as discussed: not really useful at this point

2016-12-06 19:14 UTC, fpichler approved these changes

2016-12-07 17:01 UTC, msladek approved these changes

2016-12-09 15:23 UTC, merged