Improvement create XWikiRights class
celements/celements-core pull request #91
Opened 2016-11-28 08:50 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-380

2016-11-28 12:13 UTC, msladek requested changes

2016-11-28 12:13 UTC, msladek commented on src/main/java/com/celements/model/classes/fields/BooleanField.java
> +  private final String displayFormType;
add new field to BooleanFieldTest

2016-11-28 12:13 UTC, msladek commented on src/main/java/com/celements/web/classcollections/oldcore/IOldCoreClassDef.java
> +public interface IOldCoreClassDef extends ClassDefinition {
add javadoc, XWiki classes should never be added to any ClassPackage

2016-12-05 15:22 UTC, msladek commented on src/main/java/com/celements/web/classcollections/oldcore/IOldCoreClassDef.java
> +package com.celements.web.classcollections.oldcore;
up until now we have used the package name "classes" for the new class definitions. perhaps rename the package to **com.celements.web.classes**

2016-12-05 16:44 UTC, msladek approved these changes

2016-12-06 15:17 UTC, fpichler approved these changes

2016-12-07 23:28 UTC, msladek requested changes

2016-12-07 23:28 UTC, msladek commented on src/main/java/com/celements/web/classes/oldcore/XWikiRightsClass.java
> +  public static final String FIELD_PRETTY_NAME_GROUPS = "Groups";
using Strings for fields should be discouraged, better remove them. if really needed one could always use FIELD_X.getName()

2016-12-12 13:29 UTC, msladek approved these changes

2016-12-12 13:35 UTC, merged