XObjectHandler
celements/celements-core pull request #93
Opened 2016-12-26 21:12 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-299

2016-12-27 09:18 UTC, fpichler requested changes
A very nice idea for a core improvement. Maybe add a factory method to ModelAccess to get a new XWikiXObjectHandler or a new ClassFieldXObjectHandler object easily. Overall it seams not quite finished to me. The internal FilterMap is complicated to understand, possibly fragile because of using Strings and Object types and could possibly draw more out of the ClassDefinitions and ClassField core feature.

2016-12-27 09:18 UTC, fpichler commented on src/main/java/com/celements/model/access/object/DefaultXObjectHandler.java
> +  private final Map<DocumentReference, Map<String, Set<Object>>> filterMap = new LinkedHashMap<>();
add some javadoc about what is expected to be in the filterMap. ClassDocRefs ?? and Map of?? or ??

2016-12-27 09:18 UTC, fpichler commented on src/main/java/com/celements/model/access/object/DefaultXObjectHandler.java
> +  private Map<String, Set<Object>> getValueMap(DocumentReference classRef, boolean add) {
refactor in three methods getValueMap (could return Optional), containsClassRefInFilterMap and addClassRefToFilterMap. Idea: FilterMap could be a private inner class. Add javadoc that these methods expect normalized classRefs instead of normalizing the class refs in the internal methods again and again

2016-12-27 09:18 UTC, fpichler commented on src/main/java/com/celements/model/access/object/DefaultXObjectHandler.java
> +  public XObjectHandler filter(DocumentReference classRef, String key, Object value) {
please add deprecated annotation to the implementation too

2016-12-27 09:18 UTC, fpichler commented on src/main/java/com/celements/model/access/object/DefaultXObjectHandler.java
> +public class DefaultXObjectHandler implements XObjectHandler {
split class in a XWikiXObjectHandler (do not deprecate but add a hint that better type safty can be achieved by using ClassFieldXObjectHandler) with Strings and Objects for key and values and a ClassFieldXObjectHandler only using ClassFields<T> and values T too in the FilterMap(s)

2016-12-27 11:15 UTC, ebeutler commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +        classRef).fetchFirst().orNull();
Why isn't this a @Requirement? ... I assume cyclical dependancy. If so could you add a comment, so we remember in 3 months? (maybe extract method, since it gets used quite often)

2017-07-06 16:10 UTC, msladek commented
continued on branch CELDEV-299

2017-07-06 16:10 UTC, closed without merging