checkNotTranslation error message fix
celements/celements-core pull request #96
Opened 2017-01-11 09:14 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-408

2017-01-11 11:56 UTC, fpichler requested changes

2017-01-11 11:56 UTC, fpichler commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    if (isTranslation(doc)) {
keep using MessageFormat.format but fix the wrong usage. I expect that the single quotes cause the problem. Extract the Error-Message to a constant and check in a simple unit test that the replacement with MessageFormat is working.

2017-01-12 20:43 UTC, fpichler requested changes

2017-01-12 20:43 UTC, fpichler commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    String msg = "Trying to access XObjects on translation ''{0}'' of doc ''{1}''";
please extract to constant.

2017-01-12 20:55 UTC, msladek commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    String msg = "Trying to access XObjects on translation ''{0}'' of doc ''{1}''";
what for ?

2017-01-12 20:58 UTC, fpichler commented on src/main/java/com/celements/model/access/DefaultModelAccessFacade.java
> +    String msg = "Trying to access XObjects on translation ''{0}'' of doc ''{1}''";
for better readability. You may inline instead, but do not assign a constant final string to a local variable.

2017-01-12 21:06 UTC, fpichler approved these changes

2017-01-12 22:15 UTC, merged